In [1]:
from sklearn.linear_model import LogisticRegression

# Features: [months as customer]
X = [[1], [2], [3], [8], [9], [10]]

# 0 = stays, 1 = leaves
y = [0, 0, 0, 1, 1, 1]

model = LogisticRegression()
model.fit(X, y)

print(model.predict([[9]]))
print(model.predict_proba([[9]]))

[1]
[[0.04039304 0.95960696]]


In [2]:
from sklearn.ensemble import RandomForestRegressor

X = [[500], [800], [1000], [1500], [2000]]
y = [20, 32, 40, 60, 80]  # Price in lakhs

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X, y)

print(model.predict([[1200]]))

[43.6]


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Features: hours studied
X = [[1], [2], [3], [4], [5],
     [6], [7], [8], [9], [10]]

# 0 = failed, 1 = passed
y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Actual:", y_test)
print("Predicted:", y_pred)
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, zero_division=0))
print("Recall:", recall_score(y_test, y_pred, zero_division=0))
print("F1:", f1_score(y_test, y_pred, zero_division=0))

Actual: [1, 0, 1]
Predicted: [1 0 0]
Confusion matrix:
 [[1 0]
 [1 1]]
Accuracy: 0.6666666666666666
Precision: 1.0
Recall: 0.5
F1: 0.6666666666666666


In [4]:
from sklearn.preprocessing import StandardScaler

X = [[20, 30000],
     [30, 60000],
     [40, 90000]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [3]:
from sklearn.tree import DecisionTreeClassifier

# Features: [income sufficient, good credit history]
X = [
    [1, 1],
    [1, 0],
    [0, 1],
    [0, 0],
    [1, 1],
    [0, 0]
]

# 1 = approve, 0 = reject
y = [1, 0, 0, 0, 1, 0]

model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

# New applicant: sufficient income, good credit
prediction = model.predict([[1, 1]])

print(prediction)

[1]


In [2]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

actual = [80, 60, 90, 70]

model_a = [78, 62, 88, 72]
model_b = [70, 65, 80, 75]

for name, predicted in [
    ("Model A", model_a),
    ("Model B", model_b)
]:
    mae = mean_absolute_error(actual, predicted)
    mse = mean_squared_error(actual, predicted)

    print(name)
    print("MAE:", mae)
    print("MSE:", mse)
    print()


Model A
MAE: 2.0
MSE: 4.0

Model B
MAE: 7.5
MSE: 62.5



In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

# House sizes in square feet
X = np.array([500, 600, 700, 800, 900, 1000, 1100, 1200]).reshape(-1, 1)

# House prices in lakh rupees
y = np.array([25, 30, 35, 40, 45, 50, 55, 60])

# 1. Split the data: 25% for testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# 2. Create the model
model = LinearRegression()

# 3. Train the model
model.fit(X_train, y_train)

# 4. Predict test prices
y_pred = model.predict(X_test)

# 5. Calculate errors
mae = mean_absolute_error(actual,predicted)
mse = mean_squared_error(actual,predicted)

print("Actual prices:", y_test)
print("Predicted prices:", y_pred)
print("MAE:", mae)
print("MSE:", mse)

Actual prices: [30 50]
Predicted prices: [30. 50.]
MAE: 7.5
MSE: 62.5


In [6]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

actual = [100, 200, 300]
predicted = [90, 220, 280]

mae = mean_absolute_error(actual, predicted)
mse = mean_squared_error(actual, predicted)

print("MAE:", mae)
print("MSE:", mse)

MAE: 16.666666666666668
MSE: 300.0


In [9]:
from sklearn.tree import DecisionTreeClassifier

X = [[1], [2], [3], [4], [5], [6]]
y = ["Fail", "Fail", "Fail", "Pass", "Pass", "Pass"]

model = DecisionTreeClassifier(max_depth=1,random_state=42)
model.fit(X, y)

prediction = model.predict([[2]])
print(prediction)

['Fail']


In [10]:
from sklearn.ensemble import RandomForestClassifier

X = [[1], [2], [3], [4], [5], [6]]
y = ["Fail", "Fail", "Fail", "Pass", "Pass", "Pass"]

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

print(model.predict([[2]]))
print(model.predict([[5]]))

['Fail']
['Pass']


In [11]:
from sklearn.cluster import KMeans

X = [[10], [12], [15], [80], [85], [90]]

model = KMeans(n_clusters=2, random_state=42, n_init=10)
model.fit(X)

print(model.labels_)
print(model.predict([[13], [88]]))

[0 0 0 1 1 1]
[0 1]


In [12]:
from sklearn.linear_model import LogisticRegression

X = [[1], [2], [3], [4], [5], [6]]
y = [0, 0, 0, 1, 1, 1]  # 0 = Not spam, 1 = Spam

model = LogisticRegression()
model.fit(X, y)

print(model.predict([[2]]))
print(model.predict([[5]]))

[0]
[1]


In [13]:
from sklearn.neighbors import KNeighborsClassifier

X = [[1], [2], [3], [4], [5], [6]]
y = ["Fail", "Fail", "Fail", "Pass", "Pass", "Pass"]

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, y)

print(model.predict([[4]]))

['Pass']


In [14]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

X = [[1], [2], [3], [4], [5], [6]]
y = ["Fail", "Fail", "Fail", "Pass", "Pass", "Pass"]

model = make_pipeline(StandardScaler(), SVC())
model.fit(X, y)

print(model.predict([[2]]))
print(model.predict([[5]]))

['Fail']
['Pass']
